// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsymvyjhfannieqinqaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzeW12eWpoZmFubmllcWlucWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjA3NTUsImV4cCI6MjA2NzgzNjc1NX0.sHC7JLr4RsWw61LgE3wajkDBfiAHNmAmibFvA2DFuEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});